#!/command/with-contenv bash

export PGDATA=/config/postgres

echo "Starting postgres..."

if [ -f "${PGDATA}/PG_VERSION" ] && [ $(cat "${PGDATA}/PG_VERSION" || echo "") == "9.6" ]; then
  echo "You are trying to update from a UISP version older than 1.4.0, which is not supported. Please update to a version prior to 2.4.0 first, ideally one major version at a time."
  exit 1
fi

s6-setuidgid unms postgres
