#!/usr/bin/with-contenv sh

export HOME=/home/app
export HTTP_PORT=8081
export WS_PORT=8082
export WS_SHELL_PORT=8083
export UNMS_RABBITMQ_HOST=127.0.0.1
export UNMS_RABBITMQ_PORT=5672
export UNMS_PG_HOST=127.0.0.1
export UNMS_PG_PORT=5432
export UNMS_FLUENTD_HOST=127.0.0.1
export UNMS_FLUENTD_PORT=8081
export UNMS_NETFLOW_PORT=2055
export UNMS_NGINX_HOST=127.0.0.1
export UNMS_NGINX_PORT=12345
export NODE_ENV=production
export PATH=$PATH:/home/app/unms/node_modules/.bin:/opt/rabbitmq/sbin

echo "Waiting for rabbitmq to start..."
/opt/rabbitmq/sbin/rabbitmqctl wait /var/lib/rabbitmq/mnesia/rabbit@$(hostname).pid

# wait for postgres to come up
until pg_isready; do
  echo "Waiting for postgres to come up..."
  sleep 3
done

echo "Starting unms-netflow..."

if [ "$QUIET_MODE" = "1" ]; then
  echo "Starting Netflow in quiet mode..."
  s6-setuidgid unms /home/app/netflow/node-old /home/app/netflow/index.js >> /config/unms/logs/unms.log 2>&1

else
  s6-setuidgid unms /home/app/netflow/node-old /home/app/netflow/index.js 2>&1 | tee -a /config/unms/logs/unms.log
fi
