#!/usr/bin/with-contenv sh

# Redis
[ -e /config/redis ] || mkdir -p /config/redis
chown -R unms:unms /config/redis

#SiriDB
[ -e /config/siridb ] || mv /var/lib/siridb /config/siridb
[ -d /var/lib/siridb ] && rm -rf /var/lib/siridb
ln -s /config/siridb /var/lib/siridb

# UNMS
[ -e /config/unms ] || mv /home/app/unms/data /config/unms
[ -d /home/app/unms/data ] && rm -rf /home/app/unms/data
[ -f /sharedenv ] || (echo "export UNMS_TOKEN=$(LC_CTYPE=C tr -dc "a-zA-Z0-9" < /dev/urandom | fold -w 48 | head -n 1 || true)" > /sharedenv \
&& echo "export SECRET=$(LC_CTYPE=C tr -dc "a-zA-Z0-9" < /dev/urandom | fold -w 48 | head -n 1 || true)" >> /sharedenv \
&& echo "export SECURE_LINK_SECRET=$(LC_CTYPE=C tr -dc "a-zA-Z0-9" < /dev/urandom | fold -w 100 | head -n 1 || true)" >> /sharedenv \
&& echo "export UNMS_CLI_TOKEN=$(LC_CTYPE=C tr -dc "a-zA-Z0-9" < /dev/urandom | fold -w 48 | head -n 1 || true)" >> /sharedenv)
ln -s /config/unms /home/app/unms/data

# UCRM
[ -e /config/unms/ucrm ] && chown -R unms:unms /config/unms || mv /data /config/unms/ucrm
[ -d /data ] && rm -rf /data
ln -s /config/unms/ucrm /data

# Nginx Firmware
mkdir -p /home/app/unms/public/firmwares /www
chown -R unms:unms /home/app/unms/public/firmwares
ln -s /home/app/unms/public/firmwares /www/firmwares

# Certs
[ -e /config/cert ] || mkdir -p /config/cert
[ -e /config/usercert ] || mkdir -p /config/usercert
ln -s /config/cert /cert
ln -s /config/usercert /usercert

# UNMS / UCRM Logs
[ -e /config/unms/logs ] || mkdir -p /config/unms/logs
chown -R nobody:nogroup /config/unms/logs

# Service Logs
[ -e /config/logs ] || mkdir -p /config/logs
chown -R nobody:nogroup /config/logs

# Clean cron
[ -f /var/run/crond.pid ] && rm -rf /var/run/crond.pid

# Fix hosts file
echo "127.0.0.1 unms" >> /etc/hosts

# Fix logrotate permission
chmod 644 /etc/logrotate.d/unms
chmod 644 /etc/logrotate.d/ucrm